stages:
  - run
  - build
  - deploy

image: node:18.18.2

# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

cache:
  paths:
    - godine/node_modules/

run:
  stage: run
  artifacts:
    paths:
      - build
  script:
    - cd godine
    - npm install
    - echo  "Stage run Successful".

deploy:
  stage: deploy
  script:
    - cd godine
    - npm run build
    - echo  "Stage Deploy Successful".
# test_async:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/async.spec.js

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
