stages:
  - build
  - deploy

image: node:18.18.2

before_script:
  - CI=false
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

front-end:
  stage: build
  script:
    - cd godine
    - npm install
    - npm run build
    - echo "Build Successful."
back-end:
  stage: build
  script:
    - cd godine_server
    - npm install
    - echo "Build Successful."
# deploy:
#   stage: deploy
#   script:
#     - cd godine
#     - npm install
#     - echo  "Stage Deploy Successful".
# test_async:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/async.spec.js

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production

# test:
#     stage: test
#     script: npm run test

